server:
  host: 0.0.0.0
  port: 3000

db:
  mongodb_demo:
    uri: mongodb://127.0.0.1:27017/demo
  mysql_demo:
    dialect: mysql
    host: 127.0.0.1
    port: 3306
    username: demo
    password: "123123"
    database: "demo"
    autoLoadEntities: true
    timezone: +08:00
    logging: true
  redis:
    namespace: default
    host: localhost
    port: 6379
    db: 0
